---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a new pull request, performs build and runs tests
name: 'Python Build/Test/Release'

# yamllint disable-line rule:truthy
on:
  # Trigger on tag push events
  push:
    tags:
      - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      attestations: write
    # Pinned to python-workflows v0.1.0 release commit
    # yamllint disable-line rule:line-length
    uses: lfreleng-actions/python-workflows/.github/workflows/build-test-release.yaml@518ac92728ff987d1f0edab163b1e328fd7258d7  # v0.1.0
    secrets:
      pypi_credential: ${{ secrets.PYPI_CREDENTIAL }}
      test_pypi_credential: ${{ secrets.TEST_PYPI_CREDENTIAL }}
